from .books import (
    BookContentBase,
    BookContentCreate,
    BookContentUpdate,
    BookContent,
    BookBase,
    BookCreate,
    BookImport,
    BookUpdate,
    Book,
    BookWithContents,
    BookUploadResponse,
    BookQueryIdsQuery,
    ContentPositionsQuery,
    BookDeleteRequest,
)
from .user import (
    UserBase,
    UserCreate,
    UserUpdate,
    User,
    UserLoginRequest,
)
from .note import (
    NoteCreateRequest,
    NoteResponse,
    NoteUpdateRequest,
)

from .quizz import (
    QuizzBase,
    QuizzCreate,
    QuizzUpdate,
    Quizz,
)
from .study_history import (
    ExtractedContentUpsertRequest,
    ExtractedContentResponse,
    StudyActivityCreateRequest,
    StudyActivityResponse,
)
from .ai import (
    ChatWithRAGRequest,
    ChatWithRAGResponse,
    BriefParagraphRequest,
    BriefParagraphResponse,
    GeneratingFlashcardRequest,
    GeneratingFlashcardResponse,
    GeneratingQuizzRequest,
    GeneratingQuizzResponse,
    NotebookChatRequest,
    NotebookChatResponse,
)
from .flash import (
    FlashBase,
    FlashCreate,
    Flash,
    FlashUpdate,
)
from .notebook import (
    NotebookCreateRequest,
    NotebookUpdateRequest,
    NotebookResponse,
    NotebookSourceAttachRequest,
    NotebookSourceResponse,
    NotebookDetailResponse,
)
__all__ = [
    "BookContentBase",
    "BookContentCreate",
    "BookContentUpdate",
    "BookContent",
    "BookBase",
    "BookCreate",
    "BookImport",
    "BookUpdate",
    "Book",
    "BookWithContents",
    "BookUploadResponse",
    "BookQueryIdsQuery",
    "ContentPositionsQuery",
    "BookDeleteRequest",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "User",
    "QuizzBase",
    "QuizzCreate",
    "Quizz",
    "QuizzUpdate",
    # Note schemas
    "NoteCreateRequest",
    "NoteResponse",
    "NoteUpdateRequest",
    "ExtractedContentUpsertRequest",
    "ExtractedContentResponse",
    "StudyActivityCreateRequest",
    "StudyActivityResponse",
    # AI schemas
    "ChatWithRAGRequest",
    "ChatWithRAGResponse",
    "BriefParagraphRequest",
    "BriefParagraphResponse",
    "GeneratingFlashcardRequest",
    "GeneratingFlashcardResponse",
    "GeneratingQuizzRequest",
    "GeneratingQuizzResponse",
    "NotebookChatRequest",
    "NotebookChatResponse",
    # Flashcard schemas
    "FlashBase",
    "FlashCreate",
    "Flash",
    "FlashUpdate",
    "NotebookCreateRequest",
    "NotebookUpdateRequest",
    "NotebookResponse",
    "NotebookSourceAttachRequest",
    "NotebookSourceResponse",
    "NotebookDetailResponse",
]
